name: Build obsidian plugin

on:
    push:
        # Sequence of patterns matched against refs/tags
        tags:
            - '*' # Push events to matching any tag format, i.e. 1.0, 20.15.10

env:
    PLUGIN_NAME: obsidian-music-player # Change this to the name of your plugin-id folder

jobs:
    build:
        runs-on: ubuntu-latest

        permissions:
            contents: write

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v4.0.1
              with:
                  node-version: '20.x' # You might need to adjust this value to your own version
            - name: Build
              id: build
              run: |
                  npm install
                  npm run build --if-present
                  mkdir ${{ env.PLUGIN_NAME }}
                  cp main.js manifest.json styles.css ${{ env.PLUGIN_NAME }}
                  zip -r ${{ env.PLUGIN_NAME }}.zip ${{ env.PLUGIN_NAME }}
                  ls
                  echo "tag_name=$(git tag --sort version:refname | tail -n 1)" >> $GITHUB_OUTPUT

            - name: Create Release
              id: create_release
              uses: ncipollo/release-action@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  VERSION: ${{ github.ref }}
              with:
                  artifacts: '${{ env.PLUGIN_NAME }}.zip,main.js,manifest.json,styles.css'
                  draft: false
                  prerelease: false
